--liquibase formatted sql

--changeset Rachit-9382:201
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','1','1','1');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','1','2','2');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','1','3','3');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','1','8','4');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','2','8','4');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','2','3','3');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','2','2','2');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','2','1','1');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','3','8','6');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','3','7','4');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','3','6','5');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','3','2','3');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','3','4','1');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','3','5','2');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','4','7','4');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','4','6','5');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','4','5','2');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','4','4','1');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','4','2','3');
insert into `st_sl_game_type_option_mapping` (`game_id`, `game_type_id`, `option_id`, `display_order`) values('1','4','8','6');
--rollback truncate table `st_sl_game_type_option_mapping`;

--changeset Rachit-9382:202
insert into `st_sl_schedular_merchant_mapping`(`schedular_id`,`merchant_id`,`draw_data`) values ( '1',(select merchant_id from st_sl_merchant_master where merchant_dev_name = 'TonyBet'),'{\r\n  \"WEEKLY\": {\r\n    \"THU\": {\r\n      \"1\": {\r\n        \"drawName\": \"THURSDAY-S13\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"SUN\": {\r\n      \"1\": {\r\n        \"drawName\": \"SUNDAY-S13\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    }\r\n  }\r\n}\r\n');
-- rollback delete from st_sl_schedular_merchant_mapping where schedular_id = 1 and merchant_id = (select merchant_id from st_sl_merchant_master where merchant_dev_name = 'TonyBet');

insert into `st_sl_schedular_merchant_mapping`(`schedular_id`,`merchant_id`,`draw_data`) values ( '2',(select merchant_id from st_sl_merchant_master where merchant_dev_name = 'TonyBet'),'{\r\n  \"WEEKLY\": {\r\n    \"THU\": {\r\n      \"1\": {\r\n        \"drawName\": \"THURSDAY-S10\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"SUN\": {\r\n      \"1\": {\r\n        \"drawName\": \"SUNDAY-S10\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    }\r\n  }\r\n}');
-- rollback delete from st_sl_schedular_merchant_mapping where schedular_id = 2 and merchant_id = (select merchant_id from st_sl_merchant_master where merchant_dev_name = 'TonyBet');

insert into `st_sl_schedular_merchant_mapping`(`schedular_id`,`merchant_id`,`draw_data`) values ( '3',(select merchant_id from st_sl_merchant_master where merchant_dev_name = 'TonyBet'),'{\r\n  \"WEEKLY\": {\r\n    \"MON\": {\r\n      \"1\": {\r\n        \"drawName\": \"MONDAY-S6\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"TUE\": {\r\n      \"1\": {\r\n        \"drawName\": \"TUESDAY-S6\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"WED\": {\r\n      \"1\": {\r\n        \"drawName\": \"WEDNESDAY-S6\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"THU\": {\r\n      \"1\": {\r\n        \"drawName\": \"THURSDAY-S6\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"FRI\": {\r\n      \"1\": {\r\n        \"drawName\": \"FRIDAY-S6\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"SAT\": {\r\n      \"1\": {\r\n        \"drawName\": \"SATURDAY-S6\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"SUN\": {\r\n      \"1\": {\r\n        \"drawName\": \"SUNDAY-S6\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    }\r\n  }\r\n}\r\n');
-- rollback delete from st_sl_schedular_merchant_mapping where schedular_id = 3 and merchant_id = (select merchant_id from st_sl_merchant_master where merchant_dev_name = 'TonyBet');

insert into `st_sl_schedular_merchant_mapping`(`schedular_id`,`merchant_id`,`draw_data`) values ( '4',(select merchant_id from st_sl_merchant_master where merchant_dev_name = 'TonyBet'),'{\r\n  \"WEEKLY\": {\r\n    \"MON\": {\r\n      \"1\": {\r\n        \"drawName\": \"MONDAY-S4\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"TUE\": {\r\n      \"1\": {\r\n        \"drawName\": \"TUESDAY-S4\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"WED\": {\r\n      \"1\": {\r\n        \"drawName\": \"WEDNESDAY-S4\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"THU\": {\r\n      \"1\": {\r\n        \"drawName\": \"THURSDAY-S4\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"FRI\": {\r\n      \"1\": {\r\n        \"drawName\": \"FRIDAY-S4\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"SAT\": {\r\n      \"1\": {\r\n        \"drawName\": \"SATURDAY-S4\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    },\r\n    \"SUN\": {\r\n      \"1\": {\r\n        \"drawName\": \"SUNDAY-S4\",\r\n        \"verificationDays\": -1,\r\n        \"claimStartDays\": -1,\r\n        \"claimEndDays\": -15,\r\n        \"drawDisplayType\": \"DRAW_NAME\",\r\n        \"eventStartId\": 1\r\n      }\r\n    }\r\n  }\r\n}\r\n');
-- rollback delete from st_sl_schedular_merchant_mapping where schedular_id = 4 and merchant_id = (select merchant_id from st_sl_merchant_master where merchant_dev_name = 'TonyBet');